/*
 * ─────────────────────────────────────────────────────────────
 *  EDIT THIS FILE to update the website content.
 *  No build step needed — just commit & push to GitHub.
 * ─────────────────────────────────────────────────────────────
 */

// Samaj contact details (leave a value empty "" to hide it)
const SAMAJ = {
  nameNe: "थापा श्रेष्ठ समाज",
  nameEn: "Thapa Shrestha Samaj",
  address: "Bahakha Bazar, Mandhyapur Thimi 6, Bhaktapur",
  established: "2075 B.S.",
  phone: "",      // e.g. "+977-98XXXXXXXX"
  email: "",      // e.g. "info@thapashresthasamaj.org"
  facebook: "",   // e.g. "https://facebook.com/yourpage"
  // Shows a "sample listings" notice above the offers. Set to false when real partners are added.
  showSampleNotice: true,
};

// Categories: id is referenced by each offer below
const CATEGORIES = [
  { id: "vehicle",   label: "Vehicle",        icon: "🚗", color: "#1d3a8f" },
  { id: "health",    label: "Health",         icon: "🩺", color: "#c8202f" },
  { id: "food",      label: "Food & Events",  icon: "🍲", color: "#d95a0f" },
  { id: "education", label: "Education",      icon: "📚", color: "#0f766e" },
  { id: "lifestyle", label: "Lifestyle",      icon: "💇", color: "#8e3a86" },
  { id: "home",      label: "Home Services",  icon: "🔧", color: "#7a5412" },
  { id: "shopping",  label: "Shopping",       icon: "🛍️", color: "#2e7d32" },
];

/*
 * Offer fields:
 *   id          unique text id
 *   category    one of the CATEGORIES ids
 *   title       short name of the offer
 *   badge       big label on the card, e.g. "20% OFF", "FREE"
 *   percent     number used for the "up to X% off" stat (0 if not a % discount)
 *   partner     business name
 *   location    area / address
 *   phone       optional — shows a "Call" button in the details popup
 *   valid       validity text
 *   description one or two sentences
 *   terms       list of conditions
 *   featured    true = shown first
 */
const OFFERS = [
  {
    id: "car-wash",
    category: "vehicle",
    title: "Car Wash",
    badge: "20% OFF",
    percent: 20,
    partner: "Thimi Auto Care",
    location: "Bahakha Bazar, Thimi",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Full exterior foam wash and interior vacuum for cars, jeeps and vans.",
    terms: ["Valid on regular and premium wash packages", "One wash per card per visit", "Not combinable with other promotions"],
    featured: true,
  },
  {
    id: "bill-book",
    category: "vehicle",
    title: "Bill Book Door Pick-up & Drop",
    badge: "FREE",
    percent: 0,
    partner: "Samaj Member Service Desk",
    location: "Mandhyapur Thimi 6 area",
    phone: "",
    valid: "Ongoing",
    description: "We collect your vehicle bill book (bluebook) from your home for renewal and deliver it back once done.",
    terms: ["Government renewal fees and taxes paid by member", "Pick-up within Mandhyapur Thimi 6 municipality", "Allow 3–5 working days"],
    featured: true,
  },
  {
    id: "bike-service",
    category: "vehicle",
    title: "Bike & Scooter Servicing",
    badge: "15% OFF",
    percent: 15,
    partner: "Bhaktapur Moto Works",
    location: "Thimi Chowk",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "General servicing, oil change and brake check for two-wheelers.",
    terms: ["Discount on labour charges only", "Spare parts at regular price"],
  },
  {
    id: "health-checkup",
    category: "health",
    title: "Full Body Health Check-up",
    badge: "25% OFF",
    percent: 25,
    partner: "Madhyapur Health Clinic",
    location: "Bode, Mandhyapur Thimi 6",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Complete package including blood tests, sugar, lipid profile, kidney and liver function.",
    terms: ["Book at least one day in advance", "Applicable to card holder and spouse"],
    featured: true,
  },
  {
    id: "pharmacy",
    category: "health",
    title: "Medicines at Pharmacy",
    badge: "10% OFF",
    percent: 10,
    partner: "Sanjeevani Pharmacy",
    location: "Bahakha Bazar, Thimi",
    phone: "",
    valid: "Ongoing",
    description: "Discount on prescribed and over-the-counter medicines.",
    terms: ["Not applicable on baby food and cosmetics", "Prescription required for prescribed medicines"],
  },
  {
    id: "dental",
    category: "health",
    title: "Dental Consultation",
    badge: "FREE",
    percent: 0,
    partner: "Smile Dental Care",
    location: "Thimi, Bhaktapur",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Free first consultation plus 15% off on scaling, filling and other treatments.",
    terms: ["Free consultation once per year per member", "Appointment required"],
  },
  {
    id: "eye-care",
    category: "health",
    title: "Eye Test & Spectacles",
    badge: "15% OFF",
    percent: 15,
    partner: "Clear Vision Opticals",
    location: "Thimi Chowk",
    phone: "",
    valid: "Ongoing",
    description: "Free computerised eye test and 15% off on frames and lenses.",
    terms: ["Discount not applicable on contact lenses"],
  },
  {
    id: "restaurant",
    category: "food",
    title: "Dine-in at Newari Restaurant",
    badge: "15% OFF",
    percent: 15,
    partner: "Thimi Newa Bhoye Ghar",
    location: "Bahakha Bazar, Thimi",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Authentic Newari khaja sets, bara, chatamari and more.",
    terms: ["Dine-in only", "Not valid on public holidays and festival days"],
  },
  {
    id: "catering",
    category: "food",
    title: "Bhoj & Event Catering",
    badge: "10% OFF",
    percent: 10,
    partner: "Shrestha Catering Service",
    location: "Mandhyapur Thimi 6",
    phone: "",
    valid: "Ongoing",
    description: "Catering for weddings, bratabandha, pasni and community events.",
    terms: ["Minimum 50 guests", "Advance booking of 7 days required"],
    featured: true,
  },
  {
    id: "party-palace",
    category: "food",
    title: "Party Palace Booking",
    badge: "12% OFF",
    percent: 12,
    partner: "Bhaktapur Banquet Hall",
    location: "Araniko Highway, Thimi",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Hall booking discount for weddings, receptions and family functions.",
    terms: ["Applies to hall rent only", "Subject to date availability"],
  },
  {
    id: "photography",
    category: "food",
    title: "Event Photo & Video",
    badge: "10% OFF",
    percent: 10,
    partner: "Frame Studio",
    location: "Thimi, Bhaktapur",
    phone: "",
    valid: "Ongoing",
    description: "Photography and videography packages for weddings and ceremonies.",
    terms: ["Valid on full-day packages"],
  },
  {
    id: "computer-class",
    category: "education",
    title: "Computer & IT Classes",
    badge: "20% OFF",
    percent: 20,
    partner: "Madhyapur Computer Institute",
    location: "Bode, Mandhyapur Thimi 6",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Basic computer, accounting (Tally), graphic design and coding courses.",
    terms: ["For card holder and their children", "Discount on admission and course fee"],
  },
  {
    id: "tuition",
    category: "education",
    title: "School Tuition & Bridge Course",
    badge: "15% OFF",
    percent: 15,
    partner: "Gyan Jyoti Learning Centre",
    location: "Bahakha Bazar, Thimi",
    phone: "",
    valid: "Ongoing",
    description: "Tuition for grades 1–12 and SEE bridge course preparation.",
    terms: ["Monthly fee discount", "Children of card holders only"],
  },
  {
    id: "pottery",
    category: "education",
    title: "Thimi Pottery Workshop",
    badge: "15% OFF",
    percent: 15,
    partner: "Thimi Clay Art Studio",
    location: "Pottery Square, Thimi",
    phone: "",
    valid: "Ongoing",
    description: "Hands-on traditional pottery sessions for kids and adults.",
    terms: ["Group of up to 4 per card", "Weekend slots subject to availability"],
  },
  {
    id: "salon",
    category: "lifestyle",
    title: "Salon & Beauty Parlour",
    badge: "20% OFF",
    percent: 20,
    partner: "Glow Unisex Salon",
    location: "Thimi Chowk",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Haircut, facial, threading, mehendi and bridal make-up services.",
    terms: ["Bridal packages: 10% off", "Appointment recommended"],
  },
  {
    id: "gym",
    category: "lifestyle",
    title: "Gym Membership",
    badge: "1 MONTH FREE",
    percent: 0,
    partner: "Fit Nation Gym",
    location: "Araniko Highway, Thimi",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Get one extra month free with any 6-month or annual membership.",
    terms: ["New memberships only", "Non-transferable"],
  },
  {
    id: "tailoring",
    category: "lifestyle",
    title: "Tailoring & Daura Suruwal",
    badge: "10% OFF",
    percent: 10,
    partner: "Shrestha Tailors",
    location: "Bahakha Bazar, Thimi",
    phone: "",
    valid: "Ongoing",
    description: "Stitching of daura suruwal, haku patasi, kurta and suits.",
    terms: ["Stitching charge only", "Fabric at regular price"],
  },
  {
    id: "home-repair",
    category: "home",
    title: "Electrician & Plumber Visit",
    badge: "FREE VISIT",
    percent: 0,
    partner: "Thimi Home Fix",
    location: "Mandhyapur Thimi 6",
    phone: "",
    valid: "Ongoing",
    description: "No visit charge for electrical and plumbing repairs at home.",
    terms: ["Labour and materials charged as per work", "Within Mandhyapur Thimi 6 municipality"],
  },
  {
    id: "insurance",
    category: "home",
    title: "Life & Vehicle Insurance Advice",
    badge: "FREE",
    percent: 0,
    partner: "Samaj Insurance Help Desk",
    location: "Samaj Office, Bahakha Bazar",
    phone: "",
    valid: "Ongoing",
    description: "Free guidance on choosing, renewing and claiming insurance policies.",
    terms: ["By appointment on Saturdays"],
  },
  {
    id: "grocery",
    category: "shopping",
    title: "Grocery & Daily Needs",
    badge: "5% OFF",
    percent: 5,
    partner: "Thimi Mart",
    location: "Bahakha Bazar, Thimi",
    phone: "",
    valid: "Ongoing",
    description: "Discount on groceries and household items on bills above Rs. 2,000.",
    terms: ["Minimum bill Rs. 2,000", "Not valid on already discounted items"],
  },
  {
    id: "hardware",
    category: "shopping",
    title: "Hardware & Building Materials",
    badge: "7% OFF",
    percent: 7,
    partner: "Madhyapur Hardware Suppliers",
    location: "Thimi, Bhaktapur",
    phone: "",
    valid: "Till Chaitra 2083",
    description: "Paints, sanitary items, electrical fittings and construction materials.",
    terms: ["Not applicable on cement and rods"],
  },
];
